truncate table public.ramais;

insert into public.ramais (nome, numero, cargo, setor, email, observacoes, ativo)
values
  ('Dr. Tadeu Oliveira', '2001', 'Presidente', '*Presidência', null, null, true),
  ('Dra. Rosangela', '2002', 'Vice-Presidente', '*RH', null, null, true),
  ('Amanda Miranda', '2008', 'Assistente de RH', '*RH', null, null, true),
  ('Jackeline Barbosa', '2003', 'Superintendente', '*Superintendência', null, null, true),
  ('Luana Ximenes', '2009', 'Assistente Administrativo', 'Administrativo', null, null, true),
  ('Jefferson Carvalho', '2011', '*', 'Administrativo', null, null, true),
  ('Samira Ramos', '2012', 'Assistente', 'Administrativo', null, null, true),
  ('Lavinia Sanford', '2013', 'Assistente Administrativo', 'Administrativo', null, null, true),
  ('Anne Caroline', '2018', 'Assistente Administrativo', 'Administrativo', null, null, true),
  ('Regina Bulcão', '2034', 'Gerente Administrativa', 'Administrativo', null, null, true),
  ('Luana Santos', '2015', 'Supervisora', 'Central de Relacionamento', null, null, true),
  ('Marcação', '5090', 'Fila de atendimento', 'Central de Relacionamento', null, null, true),
  ('Vendas', '5091', 'Fila de atendimento', 'Central de Relacionamento', null, null, true),
  ('Sac', '5092', 'Fila de atendimento', 'Central de Relacionamento', null, null, true),
  ('Credenciado', '5093', 'Fila de atendimento', 'Central de Relacionamento', null, null, true),
  ('Pedro Izaias', '7002', 'Auxiliar Backoffice', 'Central de Relacionamento', null, null, true),
  ('Consultórios 1 ao 3', '2318', '*', 'Clinica - Aguanambi', null, null, true),
  ('Consultórios 4 ao 8', '2319', '*', 'Clinica - Aguanambi', null, null, true),
  ('Recepção Orto', '2320', '*', 'Clinica - Aguanambi', null, null, true),
  ('Recepção Clinico', '2323', '*', 'Clinica - Aguanambi', null, null, true),
  ('Rafaele Ferreira', '2324', 'Supervisora', 'Clinica - Aguanambi', null, null, true),
  ('Consultórios 9 ao 12', '2325', '*', 'Clinica - Aguanambi', null, null, true),
  ('Consultorios Clinico', '2101', '*', 'Clinica - Bezerra', null, null, true),
  ('Consultorios Orto', '2102', '*', 'Clinica - Bezerra', null, null, true),
  ('Recepção Clinico', '2104', '*', 'Clinica - Bezerra', null, null, true),
  ('Recepção Orto', '2105', '*', 'Clinica - Bezerra', null, null, true),
  ('Recepção Clinico', '2200', '*', 'Clinica - Parangaba', null, null, true),
  ('Recepção Clinico', '2201', '*', 'Clinica - Parangaba', null, null, true),
  ('Sala de Esterilazação 1', '2202', '*', 'Clinica - Parangaba', null, null, true),
  ('Sala de Esterilazação 2', '2203', '*', 'Clinica - Parangaba', null, null, true),
  ('Sala de Esterilazação 3', '2204', '*', 'Clinica - Parangaba', null, null, true),
  ('Taissa', '2205', 'Assistente Financeiro', 'Clinica - Parangaba', null, null, true),
  ('Recepção Orto', '2206', '*', 'Clinica - Parangaba', null, null, true),
  ('Recepção Orto', '2207', '*', 'Clinica - Parangaba', null, null, true),
  ('Sala de Esterilazação 4', '2208', '*', 'Clinica - Parangaba', null, null, true),
  ('Sala de Esterilazação 5', '2209', '*', 'Clinica - Parangaba', null, null, true),
  ('Sala de Esterilazação 6', '2210', '*', 'Clinica - Parangaba', null, null, true),
  ('Thais', '2211', 'Almoxarifado', 'Clinica - Parangaba', null, null, true),
  ('Copa', '2212', 'Copa', 'Clinica - Parangaba', null, null, true),
  ('Dr. Davi Barros', '2213', 'Coodenador', 'Clinica - Parangaba', null, null, true),
  ('Charlyane', '2214', 'Supervisora Clinica', 'Clinica - Parangaba', null, null, true),
  ('Tayane / Andreza', '1000', 'Recepção', 'Clinica - Sobral', null, null, true),
  ('Consultorio', '1001', '*', 'Clinica - Sobral', null, null, true),
  ('Administração', '1002', '*', 'Clinica - Sobral', null, null, true),
  ('Vendas', '1003', '*', 'Clinica - Sobral', null, null, true),
  ('Rodrigo Leite', '2016', 'Gerente', 'Comercial', null, null, true),
  ('Tiago Rios', '2051', 'Gerente Comercial', 'Comercial', null, null, true),
  ('Sr. Antonio / Dona Jackeline', '2032', 'Serviços Gerais', 'Copa', null, null, true),
  ('John Hudson', '2020', 'Auditor Clinico', 'Credenciamento / Contas', null, null, true),
  ('Deynny Moura', '2021', 'Analista de Credenciamento', 'Credenciamento / Contas', null, null, true),
  ('Maria Daldiziela', '6002', 'Assitente', 'Credenciamento / Contas', null, null, true),
  ('Bianca Castro', '6003', 'Asistente', 'Credenciamento / Contas', null, null, true),
  ('Roberta Braga', '2006', 'Assistente de DP', 'Departamento Pessoal - DP', null, null, true),
  ('Valonia', '2007', 'Supervisora', 'Departamento Pessoal - DP', null, null, true),
  ('Dra. Sandra', '2213', 'Diretora Clinica', 'Diretoria Clinica', null, null, true),
  ('Sandra Gomes', '2004', 'Assistente', 'Financeiro', null, null, true),
  ('Gerusa Pinheiro', '2005', 'Gerente', 'Financeiro', null, null, true),
  ('Douglas Moreira', '2023', 'Assistente', 'Financeiro', null, null, true),
  ('Castelo', '2025', 'Assistente de Marketing', 'Marketing', null, null, true),
  ('Larissa de Melo', '2025', 'Coordenadora de Marketing', 'Marketing', null, null, true),
  ('-', '2050', 'Gerente', 'Novos Negocios', null, null, true),
  ('Lucas Williame', '2052', 'Assis. Comercial', 'Novos Negocios', null, null, true),
  ('Lissandra Moura', '2017', 'Recepcionista', 'Recepção - ADM', null, null, true),
  ('Sala de Reunião 02', '2029', '*', 'Salas de Reunião', null, null, true),
  ('Sala de Reunião 01', '2030', '*', 'Salas de Reunião', null, null, true),
  ('Daniel', '2028', 'Técnico', 'T.I', null, null, true),
  ('Vinicius Oliveira', '2028', 'Tecnico', 'T.I', null, null, true),
  ('Júlio Simão', '2028', 'Estagiário de T.I', 'T.I', null, null, true),
  ('Cezar Ferreira Gomes', '2031', 'Diretor de Ti', 'T.I', null, null, true);
